name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: pnpm  build

      - name: Deploy
        run: |
          set -e

          test -d out

          VERSION=$(date +%Y%m%d%H%M%S)
          RELEASE_DIR="/opt/form-pilates-web/releases/$VERSION"

          mkdir -p "$RELEASE_DIR"

          cp -R out/* "$RELEASE_DIR"

          ln -sfn "$RELEASE_DIR" \
            /opt/form-pilates-web/current

          ls -dt /opt/form-pilates-web/releases/* \
            | tail -n +6 \
            | xargs -r rm -rf
